name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package.json version
        shell: bash
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" != "${{ steps.version.outputs.VERSION }}" ]; then
            echo "Updating version from $CURRENT_VERSION to ${{ steps.version.outputs.VERSION }}"
            npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
          else
            echo "Version is already correct: $CURRENT_VERSION"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: npm run quality

      - name: Build production
        run: npm run build-prod

      - name: Build Electron app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
          name: Curlino v${{ steps.version.outputs.VERSION }} (Windows)
          body: |
            ## Curlino v${{ steps.version.outputs.VERSION }} - Windows Release
            
            ### 📥 Downloads
            - **Windows**: `Curlino Setup ${{ steps.version.outputs.VERSION }}.exe`
            
            ### 🚀 Changes
            See commit history for detailed changes in this release.
            
            ### 🔧 Installation
            - **Windows**: Download and run the `.exe` installer
            
            ### 📋 Note
            This release includes only the Windows version. macOS support will be added in a future release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
